name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run forbid-gitrepo-passing example
        run: bin/run forbid-gitrepo-passing
      - name: Run forbid-gitrepo-failing example
        run: bin/run forbid-gitrepo-failing || true
      - name: Run forbid-gitrepo-syntax-error example
        run: bin/run forbid-gitrepo-syntax-error || true
